# Generated by Django 4.1.7 on 2023-04-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passuser',
            options={'verbose_name': 'Турист', 'verbose_name_plural': 'Туристы'},
        ),
        migrations.AlterField(
            model_name='passuser',
            name='email',
            field=models.EmailField(max_length=150, verbose_name='E-mail'),
        ),
    ]
